# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""Public authored configuration contracts for Data Designer Slurm."""

from __future__ import annotations

from data_designer.slurm.config.benchmark import (
    AdaptiveRecordPolicy,
    BenchmarkAnalysisTargets,
    BenchmarkBaseRun,
    BenchmarkDeploymentCase,
    BenchmarkDeploymentOverride,
    DataDesignerSlurmBenchmarkConfig,
    FixedRecordPolicy,
)
from data_designer.slurm.config.images import (
    ClientImageInspection,
    ImageBuildRequest,
    ImageInspectionRecord,
    ImageKind,
    ImageRef,
    InstalledDistribution,
    ServingImageInspection,
)
from data_designer.slurm.config.profiles import (
    ContainerMount,
    GpuRequestMode,
    ImageBuildProfile,
    ProfileSelectionSource,
    SchedulerProfile,
    SelectedSlurmProfile,
    SlurmProfile,
    SlurmProfileCatalog,
    injected_profile,
    select_profile,
    validate_selected_profile,
)
from data_designer.slurm.config.run import (
    ArrayTasksConfig,
    BuilderInput,
    ClientConfig,
    ClientDependencies,
    DataDesignerSlurmConfig,
    DeploymentResources,
    DeploymentTopology,
    InputBindings,
    InvocationConfig,
    InvocationDiagnostics,
    LiteralEnvironmentBinding,
    LocalStdioMCPProviderConfig,
    OutputConfig,
    QueueBackpressureConfig,
    RemoteMCPProviderConfig,
    SecretRef,
    ServerDeploymentConfig,
    SubmissionConfig,
    VllmServerConfig,
)

__all__ = [
    "AdaptiveRecordPolicy",
    "ArrayTasksConfig",
    "BenchmarkAnalysisTargets",
    "BenchmarkBaseRun",
    "BenchmarkDeploymentCase",
    "BenchmarkDeploymentOverride",
    "BuilderInput",
    "ClientConfig",
    "ClientDependencies",
    "ClientImageInspection",
    "ContainerMount",
    "DataDesignerSlurmBenchmarkConfig",
    "DataDesignerSlurmConfig",
    "DeploymentResources",
    "DeploymentTopology",
    "FixedRecordPolicy",
    "GpuRequestMode",
    "ImageBuildProfile",
    "ImageBuildRequest",
    "ImageInspectionRecord",
    "ImageKind",
    "ImageRef",
    "InputBindings",
    "InstalledDistribution",
    "InvocationConfig",
    "InvocationDiagnostics",
    "LiteralEnvironmentBinding",
    "LocalStdioMCPProviderConfig",
    "OutputConfig",
    "ProfileSelectionSource",
    "QueueBackpressureConfig",
    "RemoteMCPProviderConfig",
    "SchedulerProfile",
    "SecretRef",
    "SelectedSlurmProfile",
    "ServerDeploymentConfig",
    "ServingImageInspection",
    "SlurmProfile",
    "SlurmProfileCatalog",
    "SubmissionConfig",
    "VllmServerConfig",
    "injected_profile",
    "select_profile",
    "validate_selected_profile",
]
