#!/usr/bin/env python3
# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""
Convert Jupyter notebooks (.ipynb) to Fern NotebookViewer JSON format.

Reads notebook JSON and outputs a minimal format with cells array:
  { "cells": [ { "type": "markdown"|"code", "source": "...", "language": "python" } ] }

Usage:
  python ipynb-to-fern-json.py input.ipynb -o output.json
  python ipynb-to-fern-json.py docs/notebooks/1-the-basics.ipynb -o fern/assets/notebooks/1-the-basics.json

Run after: make convert-execute-notebooks (generates .ipynb from docs/notebook_source/*.py)
"""

from __future__ import annotations

import json
import sys
from pathlib import Path


def get_language(metadata: dict) -> str:
    """Extract language from notebook metadata."""
    info = metadata.get("kernelspec", {}) or {}
    lang = info.get("language", "python")
    return "python" if lang == "python3" else lang


def convert_cell(cell: dict, default_language: str) -> dict:
    """Convert a Jupyter cell to Fern format."""
    cell_type = cell.get("cell_type", "code")
    source = cell.get("source", [])
    if isinstance(source, list):
        source = "".join(source)
    source = source.rstrip("\n")
    out: dict = {"type": cell_type, "source": source}
    if cell_type == "code":
        out["language"] = default_language
    return out


def convert_notebook(ipynb_path: Path) -> dict:
    """Convert a .ipynb file to Fern NotebookViewer format."""
    with open(ipynb_path, encoding="utf-8") as f:
        nb = json.load(f)
    metadata = nb.get("metadata", {})
    default_language = get_language(metadata)
    cells = [convert_cell(c, default_language) for c in nb.get("cells", [])]
    return {"cells": cells}


def write_ts_export(data: dict, ts_path: Path) -> None:
    """Write a .ts file that exports the notebook for MDX import (avoids JSON import)."""
    cells_json = json.dumps(data["cells"], indent=2)
    ts_path.write_text(
        f'/** Auto-generated by ipynb-to-fern-json.py - do not edit */\n'
        f'export default {{ cells: {cells_json} }};\n',
        encoding="utf-8",
    )


def main() -> int:
    args = sys.argv[1:]
    if not args or "-h" in args or "--help" in args:
        print(__doc__)
        return 0
    input_path = Path(args[0])
    output_path: Path | None = None
    if "-o" in args:
        idx = args.index("-o")
        if idx + 1 < len(args):
            output_path = Path(args[idx + 1])
    if not output_path:
        output_path = input_path.with_suffix(".json")
    if not input_path.exists():
        print(f"Error: {input_path} not found", file=sys.stderr)
        return 1
    data = convert_notebook(input_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2)
    print(f"Wrote {output_path}")
    ts_path = output_path.with_suffix(".ts")
    write_ts_export(data, ts_path)
    print(f"Wrote {ts_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
