name: Validate PR title

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

defaults:
  run:
    shell: bash -x -e -u -o pipefail {0}

permissions:
  pull-requests: read

jobs:
  semantic-pull-request:
    uses: NVIDIA-NeMo/FW-CI-templates/.github/workflows/_semantic_pull_request.yml@b0a3760374f50b3d6a7d5f8629e826dddca3b931 # v1.10.1
