name: Validate PR title

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

defaults:
  run:
    shell: bash -x -e -u -o pipefail {0}

permissions:
  pull-requests: read

jobs:
  semantic-pull-request:
    uses: NVIDIA-NeMo/FW-CI-templates/.github/workflows/_semantic_pull_request.yml@209ac7913b0419a5ccbac47b02d00fbea4939243 # v1.8.4
